name: DiscordBot
version: ${project.version}
main: me.monica.cat.discordbot.Main
perfix: [DiscordBot]
commands:
  discord:
    description: "§bDiscord bot command by catMonica."
    aliases: [dc]
    usage: "§c用法: /<command> start|stop|reload|verify|mute|setnick"
    permission-message: "You do not have /<permission>"
  dcpm:
    description: "§bDiscord private message."
    usage: "§c用法: /<command> <Discord名稱> <訊息>"
    permission-message: "You do not have /<permission>"
  color:
    description: "A color format example"
    usage: "§c用法: /<command>"
    permission-message: "You do not have /<permission>"

